export const dashboardParameters = {
    PH: {
        min: 6.5,
        max: 8.5,
        warningMin: 6.0,
        warningMax: 9.0,
        unit: "",
        currentValue: 7.0,
        description:
            "PH measures how acidic or basic your water is. The ideal range is 6.5-8.5.",
        fixInfo:
            "If your PH is too high, consider adding PH reducer. If too low, use PH increaser products.",
        weeklyData: [
            {day: "Sa", value: 6.3},
            {day: "Su", value: 6.5},
            {day: "Mo", value: 6.8},
            {day: "Tu", value: 7.0},
            {day: "We", value: 6.7},
            {day: "Th", value: 6.6},
            {day: "Fr", value: 6.8},
        ],
        lastWeekData: [
            {day: "Sa", value: 7.0},
            {day: "Su", value: 7.1},
            {day: "Mo", value: 7.3},
            {day: "Tu", value: 7.5},
            {day: "We", value: 7.8},
            {day: "Th", value: 8.1},
            {day: "Fr", value: 8.5},
        ],
        monthlyData: [
            {date: "01", value: 7.0},
            {date: "05", value: 7.2},
            {date: "10", value: 7.5},
            {date: "15", value: 7.8},
            {date: "20", value: 8.1},
            {date: "25", value: 8.7},
        ],
        hourlyData: [
            {hour: "00:00", value: 8.5},
            {hour: "04:00", value: 8.6},
            {hour: "08:00", value: 8.7},
            {hour: "12:00", value: 8.8},
            {hour: "16:00", value: 8.7},
            {hour: "20:00", value: 8.6},
        ],
    },
    TURB: {
        min: 0,
        max: 5,
        warningMin: 0,
        warningMax: 5,
        unit: "NTU",
        currentValue: 0.8,
        description:
            "Turbidity measures the cloudiness of water. Clear water should be below 5 NTU.",
        fixInfo:
            "To reduce turbidity, use flocculants, proper filtration, or let water sit to allow particles to settle.",
        weeklyData: [
            {day: "Sa", value: 2.5},
            {day: "Su", value: 2.8},
            {day: "Mo", value: 3.0},
            {day: "Tu", value: 3.2},
            {day: "We", value: 2.9},
            {day: "Th", value: 2.7},
            {day: "Fr", value: 3.1},
        ],
        lastWeekData: [
            {day: "Sa", value: 2.0},
            {day: "Su", value: 2.2},
            {day: "Mo", value: 2.3},
            {day: "Tu", value: 2.5},
            {day: "We", value: 2.7},
            {day: "Th", value: 2.9},
            {day: "Fr", value: 3.0},
        ],
        monthlyData: [
            {date: "01", value: 2.0},
            {date: "05", value: 2.3},
            {date: "10", value: 2.5},
            {date: "15", value: 2.8},
            {date: "20", value: 3.0},
            {date: "25", value: 3.2},
        ],
        hourlyData: [
            {hour: "00:00", value: 3.0},
            {hour: "04:00", value: 3.1},
            {hour: "08:00", value: 3.2},
            {hour: "12:00", value: 3.3},
            {hour: "16:00", value: 3.2},
            {hour: "20:00", value: 3.1},
        ],
    },

    TEMP: {
        min: 10,
        max: 18.5,
        warningMin: 8,
        warningMax: 20,
        unit: "°C",
        currentValue: 15.0,
        description:
            "Water temperature affects oxygen levels and aquatic life. Ideal range is 10-18.5°C.",
        fixInfo:
            "Use heaters or coolers to maintain optimal temperature depending on climate and purpose.",
        weeklyData: [
            {day: "Sa", value: 21.0},
            {day: "Su", value: 21.5},
            {day: "Mo", value: 22.0},
            {day: "Tu", value: 22.3},
            {day: "We", value: 22.5},
            {day: "Th", value: 22.2},
            {day: "Fr", value: 21.8},
        ],
        lastWeekData: [
            {day: "Sa", value: 20.0},
            {day: "Su", value: 20.5},
            {day: "Mo", value: 21.0},
            {day: "Tu", value: 21.3},
            {day: "We", value: 21.5},
            {day: "Th", value: 21.2},
            {day: "Fr", value: 20.8},
        ],
        monthlyData: [
            {date: "01", value: 20.0},
            {date: "05", value: 20.8},
            {date: "10", value: 21.5},
            {date: "15", value: 22.0},
            {date: "20", value: 22.2},
            {date: "25", value: 22.3},
        ],
        hourlyData: [
            {hour: "00:00", value: 21.8},
            {hour: "04:00", value: 21.5},
            {hour: "08:00", value: 22.0},
            {hour: "12:00", value: 22.3},
            {hour: "16:00", value: 22.5},
            {hour: "20:00", value: 22.0},
        ],
    },
    DO: {
        min: 5,
        max: 8,
        warningMin: 4,
        warningMax: 9,
        unit: "mg/L",
        currentValue: 6.5,
        description:
            "Dissolved Oxygen (DO) measures oxygen available for aquatic life. Ideal range is 5-8 mg/L.",
        fixInfo:
            "Increase DO by adding aeration, water movement, or reducing organic waste and temperatures.",
        weeklyData: [
            {day: "Sa", value: 6.2},
            {day: "Su", value: 6.5},
            {day: "Mo", value: 6.7},
            {day: "Tu", value: 6.8},
            {day: "We", value: 6.8},
            {day: "Th", value: 6.7},
            {day: "Fr", value: 6.6},
        ],
        lastWeekData: [
            {day: "Sa", value: 5.8},
            {day: "Su", value: 6.0},
            {day: "Mo", value: 6.2},
            {day: "Tu", value: 6.3},
            {day: "We", value: 6.5},
            {day: "Th", value: 6.6},
            {day: "Fr", value: 6.7},
        ],
        monthlyData: [
            {date: "01", value: 5.8},
            {date: "05", value: 6.0},
            {date: "10", value: 6.3},
            {date: "15", value: 6.5},
            {date: "20", value: 6.7},
            {date: "25", value: 6.8},
        ],
        hourlyData: [
            {hour: "00:00", value: 6.6},
            {hour: "04:00", value: 6.5},
            {hour: "08:00", value: 6.7},
            {hour: "12:00", value: 6.8},
            {hour: "16:00", value: 6.9},
            {hour: "20:00", value: 6.7},
        ],
    },
    TDS: {
        min: 300,
        max: 1000,
        warningMin: 200,
        warningMax: 1200,
        unit: "mg/L",
        currentValue: 450,
        description:
            "Total Dissolved Solids (TDS) measures dissolved minerals. Ideal range is 300-1000 mg/L.",
        fixInfo:
            "Use reverse osmosis or water softeners to reduce high TDS. For low TDS, add mineral supplements.",
        weeklyData: [
            {day: "Sa", value: 290},
            {day: "Su", value: 300},
            {day: "Mo", value: 310},
            {day: "Tu", value: 320},
            {day: "We", value: 315},
            {day: "Th", value: 305},
            {day: "Fr", value: 310},
        ],
        lastWeekData: [
            {day: "Sa", value: 270},
            {day: "Su", value: 275},
            {day: "Mo", value: 280},
            {day: "Tu", value: 285},
            {day: "We", value: 290},
            {day: "Th", value: 295},
            {day: "Fr", value: 300},
        ],
        monthlyData: [
            {date: "01", value: 270},
            {date: "05", value: 280},
            {date: "10", value: 290},
            {date: "15", value: 300},
            {date: "20", value: 310},
            {date: "25", value: 320},
        ],
        hourlyData: [
            {hour: "00:00", value: 315},
            {hour: "04:00", value: 318},
            {hour: "08:00", value: 320},
            {hour: "12:00", value: 322},
            {hour: "16:00", value: 321},
            {hour: "20:00", value: 318},
        ],
    },
};