export let tanks = [
    {
        id: 1,
        name: "Tank 1",
        location: "El Nozha",
        ph: 5.3,
        do: 6.5,
        temp: 19,
        tds: 450,
        turb: 0.8,
        lastUpdate: new Date().toISOString(),
    },
    {
        id: 2,
        name: "Tank 2",
        location: "Maadi",
        ph: 7.2,
        do: 4.8,
        temp: 15,
        tds: 1100,
        turb: 6,
        lastUpdate: new Date().toISOString(),
    },
    {
        id: 3,
        name: "Tank 3",
        location: "Heliopolis",
        ph: 8.1,
        do: 7.2,
        temp: 17,
        tds: 750,
        turb: 1.2,
        lastUpdate: new Date().toISOString(),
    },
];